---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minecraft Spigot Server'


Parameters:
  AMI:
    Description: AMI for the stack
    Type: AWS::EC2::Image::Id
  Release:
    Description: The release to grab
    Type: String
    
   
Resources:
  SpigotLoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SpigotLBSecGroup
      GroupDescription: SpigotLBSecGroup
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/32
          FromPort: 25565
          ToPort: 25565
          IpProtocol: tcp
      VpcId: vpc-a673b5c2
  SpigotSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SpigotSecGroup
      GroupDescription: SpigotSecGroup
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 25565
          ToPort: 25565
          IpProtocol: tcp
      VpcId: vpc-a673b5c2
  SpigotListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref SpigotTargetGroup
      LoadBalancerArn: !Ref SpigotLoadBalancer
      Port: 25565
      Protocol: TCP
  SpigotLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      IpAddressType: ipv4
      Name: SpigotLoadBalancer
      SubnetMappings: 
        - AllocationId: eipalloc-0359a1de15a0bec4f
          SubnetId: subnet-42c51c1b
     # SecurityGroups: 
     #   - !Ref SpigotLoadBalancerSecurityGroup
      Type: network
  SpigotTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      Name: SpigotTargetGroup
      Port: 25565
      Protocol: TCP
      Targets: 
        - Id: !Ref SpigotInstance
      VpcId: vpc-a673b5c2
  SpigotInstance:
    Type: AWS::EC2::Instance
    Properties: 
      Tags:
           - Value: !Ref Release
             Key: Release
      ImageId: !Ref AMI
      InstanceType: r6g.medium
      KeyName: Jenkins
      Monitoring: true
      IamInstanceProfile: Ec2Role
      SecurityGroupIds: 
        - !Ref SpigotSecurityGroup
      UserData: 
        Fn::Base64:
          !Sub |
            #!/bin/bash
            exec >> /var/log/userdata.log
            exec 2>%1
            source /etc/profile

            TAG_VALUE="${Release}"

            EFS=$(aws efs describe-file-systems  --query "FileSystems[?Tags[?Value=='$TAG_VALUE']].FileSystemId" | sed 's/[]["]//g')
            mount -t efs $EFS /usr/local/ec2-user/Spigot/

            LOCAL_ARTIFACT="/home/ec2-user/ansible_bootstrap.tar.gz"
            aws s3 cp s3://fablemc-artifacts/MC-Server-deployment/${Release}/ansible_bootstrap.tar.gz $LOCAL_ARTIFACT
            tar -zxvf $LOCAL_ARTIFACT -C  /home/ec2-user
            ansible-playbook -i localhost, --connection=local -u ec2-user -t survival /home/ec2-user/Ansible/spigot-server.yml --extra-vars "" -v


            
